### PR TITLE
Fix handling of nullable mandatory arguments

### PR DESCRIPTION
**Pull request by fauvel**

### CODE REVIEW

**Comment by fauvel** [comment]
@tomaszdurka please review. Mocking a class was not possible so far if a method had an argument with a default value preceding a mandatory argument.

**Comment by tomaszdurka** [comment]
Ok looking at the code, what is difference between having default value and optional? Just a bit confused. 

Not sure why we need the optional parameter for ParameterBlock, shall we remove it?
From my experiment optional is just for knowing if you should pass the param or not. In terms of generating the code it doesn't matter. So my mistake.

Experiment:
```
function foo($foo = 1, $bar, $zoo = 3) {};
php > foreach ((new ReflectionFunction('foo'))->getParameters() as $parameter) { var_dump($parameter->getName(), $parameter->isOptional(), $parameter->isDefaultValueAvailable()); }; 
string(3) "foo"
bool(false)
bool(true)
string(3) "bar"
bool(false)
bool(false)
string(3) "zoo"
bool(true)
bool(true)
```

So let's remove the optional param from ParameterBlock?

**Comment by tomaszdurka** [comment]
On the second thought we need some value to know if passed `$defaultValue = null` is a default value or not. So better keep optional, but convert it to boolean `defaultValueAvailable`.

@fauvel agree?

**Comment by fauvel** [comment]
In my understanding, “optional parameters” in the sense of the reflection class are parameters with a default value that only have other parameters with a default value after them in the method signature. So `$a` is optional in `foo($a = 1, $b = 2)` but not in `bar($a = 1, $b)`. Currently the code generator is broken in the latter case.

**Comment by fauvel** [comment]
What would you like to change in my PR exactly?

**Comment by fauvel** [comment]
Do you only want to rename `$optional` to `$defaultValueAvailable`? Sgtm!

**Comment by fauvel** [comment]
@tomaszdurka please review!

**Comment by tomaszdurka** [comment]
Yes, exactly. I think it's better for parameter itself, it cannot know if it's optional as it doesn't know where it is in the signature.

Thanks!

**Comment by tomaszdurka** [comment]
Loose thoughts:

Btw always thinking how to make things like that single argument `$defaultValue`, instead of two `$defaultValueAvailable = null, $defaultValue = null`.

Probably one choice is to have simple value holder.

```php
foo function(ValueHolder $defaultValue = null) {};

foo(null); // no default
foo(new ValueHolder(null)); // default null

```

**Pull request merged**
